### ISSUE TITLE
Can I ask you a question about the runtime environment for this open-source code?

### ISSUE THREAD

**Issue by RobinLiuZX** [CurryYuan/ZSVG3D#4]
Hi! I am very interested in your work. I would like to know what model of graphics card your work is running on and how much video memory it uses. Can it run on an NVIDIA 3090?

**Comment by CurryYuan** [comment]
Hi, it can run on 3090 if you preprocess the object features.

**Comment by RobinLiuZX** [comment]
Thank you very much！
