### ISSUE TITLE
Question about the LLM in codes.

### ISSUE THREAD

**Issue by Leon1207** [CurryYuan/ZSVG3D#5]
Thank you very much for your excellent work. Could you please provide an example code for LLM calling? Thank you so much!

**Comment by CurryYuan** [comment]
I have uploaded the visual programming generation [code](https://github.com/CurryYuan/ZSVG3D?tab=readme-ov-file#visual-programming-generation).

**Comment by Leon1207** [comment]
Thanks!

**Comment by Leon1207** [comment]
Hi! Can I ask about the pytorch and pytorch3d version you used? Thanks!

**Comment by CurryYuan** [comment]
The code is tested on Ubuntu 18.04 with following package, but should also work with other versions.
```bash
python==3.9.12
pytorch==1.11.0
pytorch3d==0.7.2
langchain==0.2.1
```
